### ISSUE TITLE
Configure error on Mac

### ISSUE THREAD

**Issue by cdeil** [cta-observatory/flexIRF#1]
Currently configure on latest Mac gives the following error:
```
configure: error: --with-universal-archs without --enable-universalsdk.
```
Full log: https://gist.github.com/cdeil/7790804e0037ff83394b#file-gistfile1-txt-L125

@TarekHC - I know I mentioned via email that I could fix Mac build issues. But now that I think about it ... I really hate GNU autotools and my understanding is that it look like CTA will use [cmake](https://cmake.org/), so fixing such issues in an autotools build isn't time well spent.

There's some example repos that use cmake at https://github.com/cta-observatory and for Python wrappers a tutorial at https://github.com/gammapy/PyGamma15/tree/gh-pages/tutorials/cmake_python_wrapper

@TarekHC - If you don't want to spend your time with build issues now (fixing this one or switching to cmake), but still want to give people like me that have a Mac a chance to look at your stuff, maybe you could share FITS example files in this repo or a separate repo? This would be even more valuable to me than being able to run your code.

Just as an example, here's some example files we have:
https://github.com/gammapy/gammapy-extra/tree/master/datasets/hess-crab4-pa
which correspond to the data model / formats described here:
http://gamma-astro-data-formats.readthedocs.org/en/latest/

Some time in March, once the spec and example files are in a bit better shape, we'll move the example files to the https://github.com/open-gamma-ray-astro/gamma-astro-data-formats repo and link to them from the spec.

**Comment by TarekHC** [comment]
Hi Christoph, 

In the past we used to built the repository with cmake, but I found complications in the process of wrapping the code with swig (while I was still trying), and decided to use autoconf/make. So it wont be too hard to go back to cmake.

Ok, I will add a folder with some examples somewhere. Although there seems to be consensus to go for the "gammalib-like" FITS serialization, and these examples currently use a different one (IMAGE HDUs for the IRF element values).

**Comment by cdeil** [comment]
> In the past we used to built the repository with cmake, but I found complications in the process of wrapping the code with swig (while I was still trying), and decided to use autoconf/make. So it wont be too hard to go back to cmake.

Have a look at https://github.com/gammapy/PyGamma15/tree/gh-pages/tutorials/cmake_python_wrapper
And you could ping @jacquemier on Github with any cmake / Swig / Python issues that come up.

@jacquemier - FYI: This repo is a prototype for the CTA instrument response function (IRF) code.

> Ok, I will add a folder with some examples somewhere. Although there seems to be consensus to go for the "gammalib-like" FITS serialization, and these examples currently use a different one (IMAGE HDUs for the IRF element values).

I wouldn't say that that.
Personally I think it's too easy to make a choice.
There's important things missing in the current prototypes.
E.g. what if we want to have some smooth interpolation options and need to serialise those as axis info in the FITS files?
And other things as well.
In those cases having something that's less standardised like your approach or a different approach altogether might become necessary.

So I think it's **very** important to have example files in your format, then sit down together and try to add what we need to either format and see which works better.

One more thing you could do is to run `ftlist irf.fits H`, `ftlist irf.fits C` and `ftlist irf.fits K` to print the basic info about the FITS files and put those in `README.md` files in the folders with the IRFs.
This is very convenient to have for discussions ... we have URLs to link to when discussing details.

**Comment by TarekHC** [comment]
> E.g. what if we want to have some smooth interpolation options and need to serialise those as axis info in the FITS files?
And other things as well.
In those cases having something that's less standardised like your approach or a different approach altogether might become necessary.

Good to know. I will add another example showing how I was proposing to handle axis parameterizations (for now, very naively). 

> So I think it's very important to have example files in your format, then sit down together and try to add what we need to either format and see which works better.

> One more thing you could do is to run ftlist irf.fits H, ftlist irf.fits C and ftlist irf.fits K to print the basic info about the FITS files and put those in README.md files in the folders with the IRFs.
This is very convenient to have for discussions ... we have URLs to link to when discussing details.

Great, that's an excellent idea. I'm not sure if I will be able to find the time before wednesday, but it's definitely in my to-do list.

**Comment by TarekHC** [comment]
Ok, I finished the autoconf->cmake port. I also tested the compilation in a colleagues laptop, so it should compile now.

@cdeil, if you can test the compilation and confirm it works, I could close the issue. Thanks!

**Comment by cdeil** [comment]
Yes, it works for me on Mac. Thank you!

Before closing this issue, could you update the info here a bit?
https://github.com/cta-observatory/flexIRF#installation

Is this how you build it now?
```
$ ./setup.sh
$ cd build && make all && cd ..
```

**Comment by TarekHC** [comment]
Excellent!

I'll update it now then. First ever Github issue closed! :)
