### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cdeil** [cta-observatory/flexIRF#11]
Could you please add an open-source license?

If you don't care, I recommend MIT.

**Comment by TarekHC** [comment]
Argh... Thanks for reminding me... I will do it and close this issue after Easter!

**Comment by cdeil** [comment]
All that's needed is one line in the README:
"The license for the flexIRF package is MIT, see the LICENSE file"
and copy & paste this file into your repo:
https://github.com/cdeil/sphinx-tutorial/blob/master/LICENSE

**Comment by TarekHC** [comment]
I have been telling myself that I should devote some time to make sure to understand the meaning of each license, and not just copy pasting one... Although I never will find the time... I will do it soon!!

**Comment by TarekHC** [comment]
After the discussion with IFAE and ASTERICS people, the code was finally allowed to be licensed as an open Apache v2 license.

Issue closed.

**Comment by cdeil** [comment]
Great! Thank you for taking the time to achieve an open-source license for this!

**Comment by TarekHC** [comment]
Yes! Thank you for pushing in this direction. I really feel as I'm supporting a "greater good"...  :)

In the end I chose Apache v2 (after some interesting reading). I see everywhere that MIT/BSD are "sufficient" for most projects... As usually most code packages are not patentable. But I don't care about the length of the LICENSE file, and it is perfectly compatible with other "free" open source licenses.
