### ISSUE TITLE
Generalise is_log to scale

### ISSUE THREAD

**Issue by cdeil** [cta-observatory/flexIRF#5]
As I mentioned in the call just now, I think having an is_log flag isn't a great solution.

How about having a scales option with linear and log for now.
For offset also sqrt scale might be useful.

With scales I mean something like this:
https://github.com/mbostock/d3/wiki/Scales
i.e. a way to transform pixel to world coordinates for 1D axes.

**Comment by TarekHC** [comment]
Ok, I just implemented a SCALE keyword (deprecating the isLog flag). The code now has a "ScaleType" enum that contains different allowed scales (for now kLinear, kLog10, kSqrt). All macros and fits files were updated to support it.
